sudo: false

language: ruby

rvm:
  - 2.2.2

cache:
  - bundler

gemfile:
  - Gemfile

env:
  global:
    RAILS_ENV=test

script:
  - bundle exec rake db:drop db:create db:migrate
  - bundle exec rake ci:travis
